### ISSUE TITLE
Fix the first release

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACEfriction.jl#2]
@MatthiasSachs  Can you please fix the release tag to 0.0.1 -- currently it is 0.0.01

**Comment by MatthiasSachs** [comment]
Hi @cortner, I just fixed that. Somehow, when I created the release yesterday, I had the impression that GitHub was forcing the format to v0.0.01 (since I tried to correct it once), but when I edited it just now again, it accepted the version number format of "v0.0.1".
